import { createFileRoute } from "@tanstack/react-router";
import { Check, ImagePlus, MoveRight, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { imagery, pageMeta } from "@/lib/gallery-data";
import { useGallery } from "@/components/site-shell";

export const Route = createFileRoute("/bespoke")({ head: () => pageMeta("Bespoke Studio", "Create a personal handcrafted lampshade with your photograph, artwork or textile.", "/bespoke"), component: BespokePage });

function BespokePage() {
  const { addToCart } = useGallery(); const [step, setStep] = useState(1); const [shape, setShape] = useState("Round"); const [size, setSize] = useState(30); const [finish, setFinish] = useState("Pearl linen"); const [piping, setPiping] = useState("Cognac"); const [preview, setPreview] = useState<string>(); const [added, setAdded] = useState(false);
  const price = useMemo(() => 495 + ({ 20: 0, 30: 150, 50: 400 }[size] ?? 0) + (finish === "Silk" ? 85 : 0), [size, finish]);
  const upload = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setPreview(typeof reader.result === "string" ? reader.result : undefined); reader.readAsDataURL(file); };
  return <><header className="section-shell pb-12 pt-20 sm:pt-28"><p className="editorial-kicker">Bespoke studio</p><div className="mt-4 grid gap-7 lg:grid-cols-2"><h1 className="editorial-title text-6xl sm:text-8xl">Your story,<br/><i>shaped by light.</i></h1><p className="max-w-lg self-end text-sm leading-8 text-muted-foreground">Build a personal shade in four considered steps. Every design is reviewed and refined by our studio before production.</p></div></header>
    <section className="border-y border-border"><div className="section-shell grid lg:grid-cols-[.8fr_1.2fr]"><div className="relative min-h-[430px] overflow-hidden bg-muted lg:min-h-[720px]"><img src={preview ?? imagery.collectionImage} width={1808} height={1200} alt="Bespoke lampshade preview" className="absolute inset-0 size-full object-cover object-right" /><div className="absolute inset-10 border border-[oklch(1_0_0/.55)]"><span className="absolute left-1/2 top-1/2 h-2/3 w-3/5 -translate-x-1/2 -translate-y-1/2 rounded-[50%_50%_18%_18%] border border-dashed border-[oklch(1_0_0/.8)]" /></div><div className="absolute bottom-5 left-5 bg-admin px-3 py-2 text-[9px] uppercase tracking-[0.15em] text-admin-foreground">Live composition preview</div></div>
      <div className="px-5 py-10 sm:px-12 lg:px-16"><div className="mb-10 flex justify-between border-b border-border pb-5">{[1,2,3,4].map((n) => <Button key={n} variant="concept" size="xs" className="text-foreground aria-pressed:text-accent" aria-pressed={step === n} onClick={() => setStep(n)}>0{n}</Button>)}</div>
        {step === 1 && <Step title="Shape & scale" number="01"><OptionGroup label="Shape" options={["Round", "Oval"]} selected={shape} onSelect={setShape}/><OptionGroup label="Diameter" options={[20,30,50]} selected={size} onSelect={setSize} suffix=" cm" /></Step>}
        {step === 2 && <Step title="Your image" number="02"><label className="mt-8 flex min-h-64 cursor-pointer flex-col items-center justify-center border border-dashed border-border bg-muted/40 p-8 text-center hover:border-accent"><input type="file" accept="image/*" className="sr-only" onChange={(event) => upload(event.target.files?.[0])}/>{preview ? <><ShieldCheck className="size-7 text-accent"/><p className="mt-4 font-display text-2xl">High resolution verified</p><p className="mt-2 text-xs text-muted-foreground">Click to choose another image</p></> : <><ImagePlus className="size-7"/><p className="mt-4 font-display text-2xl">Drop your image here</p><p className="mt-2 text-xs text-muted-foreground">JPG, PNG or TIFF · maximum 20MB</p></>}</label></Step>}
        {step === 3 && <Step title="Finish & piping" number="03"><OptionGroup label="Exterior" options={["Pearl linen", "Wool felt", "Silk"]} selected={finish} onSelect={setFinish}/><OptionGroup label="Leather piping" options={["Cognac", "Natural", "Ink"]} selected={piping} onSelect={setPiping}/></Step>}
        {step === 4 && <Step title="Your composition" number="04"><dl className="mt-8 space-y-4 border-y border-border py-6 text-xs"><div className="flex justify-between"><dt className="text-muted-foreground">Form</dt><dd>{shape} · {size} cm</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Finish</dt><dd>{finish} · {piping}</dd></div><div className="flex justify-between font-medium"><dt>Estimated price</dt><dd className="font-display text-2xl">€ {price}</dd></div></dl><p className="mt-6 text-xs leading-6 text-muted-foreground">Je ontvangt altijd eerst een digitale proef ter goedkeuring per e-mail/WhatsApp vóór start productie.</p><Button variant="gallery" className="mt-7 w-full" onClick={() => { addToCart(); setAdded(true); }}>{added ? <><Check/>Toegevoegd</> : "Voeg toe aan winkelmand"}</Button></Step>}
        <div className="mt-12 flex justify-between"><Button variant="quiet" disabled={step === 1} onClick={() => setStep((s) => Math.max(1, s - 1))}>Back</Button>{step < 4 && <Button variant="gallery" onClick={() => setStep((s) => Math.min(4, s + 1))}>Continue <MoveRight /></Button>}</div>
      </div></div></section></>;
}

function Step({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <div className="animate-rise"><p className="editorial-kicker">Step {number}</p><h2 className="editorial-title mt-3 text-4xl sm:text-5xl">{title}</h2>{children}</div>; }
function OptionGroup<T extends string | number>({ label, options, selected, onSelect, suffix = "" }: { label: string; options: T[]; selected: T; onSelect: (value: T) => void; suffix?: string }) { return <div className="mt-8"><p className="mb-3 text-[10px] uppercase tracking-[0.16em] text-muted-foreground">{label}</p><div className="grid grid-cols-3 gap-2">{options.map((option) => <Button key={option} variant="quiet" className="h-12 px-2 text-[10px] aria-pressed:border-accent aria-pressed:text-accent" aria-pressed={selected === option} onClick={() => onSelect(option)}>{option}{suffix}</Button>)}</div></div>; }