import { createFileRoute } from "@tanstack/react-router";
import { CircleDot, Leaf, MapPin, Recycle } from "lucide-react";
import { imagery, pageMeta } from "@/lib/gallery-data";

export const Route = createFileRoute("/our-craft")({ head: () => pageMeta("Our Craft", "Inside the Dutch atelier: local materials, ceramic forms, wool felt and our leather stitched signature.", "/our-craft"), component: CraftPage });

function CraftPage() { return <>
  <section className="section-shell py-20 sm:py-28"><p className="editorial-kicker">Made in the Netherlands</p><h1 className="editorial-title mt-5 max-w-5xl text-6xl sm:text-8xl">Matter, patience<br/>and the human hand.</h1></section>
  <section className="grid min-h-[72svh] lg:grid-cols-[1.35fr_.65fr]"><div><img src={imagery.craftImage} width={1600} height={1200} alt="ING & YVE leather piping stitched by hand" className="size-full object-cover" /></div><div className="flex items-end bg-primary p-8 text-primary-foreground sm:p-14"><div><p className="font-display text-7xl text-accent">99%</p><h2 className="mt-5 font-display text-3xl">Dutch-sourced materials</h2><p className="mt-5 text-sm leading-8 opacity-70">From wool felt and vegetable-tanned leather to clay and hardware, our material journey stays remarkably close to home.</p></div></div></section>
  <section className="section-shell py-24 sm:py-36"><div className="grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-4">{[[MapPin,"Close to home","Shorter chains, known makers and materials selected at their source."],[Recycle,"Circular by design","Replaceable shades, repairable fittings and forms intended to endure."],[CircleDot,"A stitched signature","Every leather edge is double stitched slowly, visibly and by hand."],[Leaf,"Natural texture","Wool felt, clay and wood bring depth without unnecessary finish."]].map(([Icon,title,text]) => { const CraftIcon = Icon as typeof MapPin; return <article key={title as string} className="bg-background p-8 sm:min-h-72"><CraftIcon className="size-5 stroke-1 text-accent"/><h2 className="mt-12 font-display text-2xl">{title as string}</h2><p className="mt-4 text-xs leading-7 text-muted-foreground">{text as string}</p></article>; })}</div></section>
  <section className="bg-surface"><div className="section-shell grid items-center gap-14 py-24 lg:grid-cols-2"><div><p className="editorial-kicker">Ceramic foundations</p><h2 className="editorial-title mt-5 text-5xl sm:text-6xl">No mould.<br/>No repetition.</h2><p className="mt-8 max-w-lg text-sm leading-8 text-muted-foreground">Our bases are built through a dialogue with clay. Finger marks, firing variation and the movement of glaze remain visible. What industry calls inconsistency, we recognize as life.</p></div><div className="image-reveal aspect-[4/3]"><img src={imagery.collectionImage} width={1808} height={1200} loading="lazy" alt="Handmade ceramic lamp forms" className="size-full object-cover object-left"/></div></div></section>
</>; }